# Generated by Django 3.1 on 2020-10-31 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('neigbour', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
                ('Profilephoto', models.ImageField(upload_to='')),
                ('Email', models.CharField(max_length=30)),
                ('Phone', models.IntegerField()),
                ('Neighbourhood', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='neigbour.neighbourhood')),
            ],
        ),
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
                ('category', models.CharField(max_length=60)),
                ('Description', models.CharField(max_length=30)),
                ('Email', models.CharField(max_length=30)),
                ('Phone', models.IntegerField()),
                ('Neighbourhood', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='neigbour.neighbourhood')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='neigbour.user')),
            ],
        ),
    ]
