# Generated by Django 3.1 on 2020-11-01 04:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('neigbour', '0002_business_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='Name',
        ),
        migrations.AddField(
            model_name='user',
            name='user',
            field=models.ForeignKey(default = 1, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
    ]
