# Generated by Django 3.1 on 2020-11-03 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neigbour', '0006_neighbourhood_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='neighbourhood',
            name='healthcontact',
            field=models.CharField(default='0702216491', max_length=13),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='neighbourhood',
            name='securitycontact',
            field=models.CharField(default='0702164918', max_length=13),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='business',
            name='Phone',
            field=models.CharField(max_length=13),
        ),
        migrations.AlterField(
            model_name='user',
            name='Email',
            field=models.EmailField(max_length=30),
        ),
        migrations.AlterField(
            model_name='user',
            name='Phone',
            field=models.CharField(max_length=13),
        ),
    ]
